# Generated by Django 5.2.14 on 2026-05-15 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'created_at'], name='portfolio_c_user_id_687ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['user', 'created_at'], name='portfolio_p_user_id_a841d2_idx'),
        ),
        migrations.AddIndex(
            model_name='workhistory',
            index=models.Index(fields=['user', 'start_date'], name='portfolio_w_user_id_bfd071_idx'),
        ),
    ]
