# Generated by Django 5.2.14 on 2026-05-15 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='projects.project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='proposals.contract'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='proposalnegotiationmessage',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='proposalnegotiationmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['contract', 'created_at'], name='proposals_m_contrac_46e8db_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['project', 'created_at'], name='proposals_p_project_ed03b8_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['freelancer', 'created_at'], name='proposals_p_freelan_96c135_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status', 'created_at'], name='proposals_p_status_3eda73_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('project', 'freelancer'), name='uniq_proposal_project_freelancer'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client', 'started_at'], name='proposals_c_client__2c8742_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['freelancer', 'started_at'], name='proposals_c_freelan_55f5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'started_at'], name='proposals_c_status_6ed597_idx'),
        ),
    ]
